### ISSUE TITLE
Implementing iteration based url shortner.

### ISSUE THREAD

**Issue by rutvikpadhiyar000** [ksh168/smolink-url_shortener#21]
We can implement a url shortner based on iteration.
This way we can avoid checking uniqueness for each new url generated.

**Comment by ksh168** [comment]
Hmm. Nice. I'll assign this issue to you. You can start working on it.

**Comment by ksh168** [comment]
@rutvikpadhiyar000 you tried in right direction and your efforts are appreciated. But we can't consider since this is a big security issue as someone can just write a script and as all the URLs are in series, one can perform DDOS attack our website very easily thus rendering it completely inaccessible.
This method cannot be used.
